apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: image-name
      type: string
  tasks:
    # 1. Step to clone the repository source
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)

    # 2. Step for npminstall (running npm installation)
    - name: npminstall
      runAfter:
        - clone
      taskRef:
        name: npm-task
      workspaces:
        - name: source
          workspace: shared-workspace

    # 3. Step for running unit tests (Jasmine)
    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine-task
      workspaces:
        - name: source
          workspace: shared-workspace

    # 4. Step for build tasks (using Buildah)
    - name: build
      runAfter:
        - tests
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
