apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-task
spec:
  workspaces:
    - name: source
  steps:
    - name: install-dependencies
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        npx jasmine
